[package]
name = "nitesh-poudel-portfolio"
version = "1.0.0"
edition = "2024"
publish = false

[dependencies]
gloo-timers = { version = "0.3", features = ["futures"] }
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = ["Clipboard", "Document", "Element", "HtmlElement", "MediaQueryList", "Navigator", "Storage", "Window"] }
yew = { version = "0.23", features = ["csr"] }
yew_icons = { version = "0.10", default-features = false, features = ["lucide", "simple_icons"] }
